<?php

namespace Database\Seeders;

use App\Models\Device;
use App\Models\Category;
use Illuminate\Database\Seeder;

class DeviceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $devices = [
            // Laptops
            [
                'name' => 'MacBook Pro 16"',
                'description' => 'Latest MacBook Pro with M2 chip, perfect for video editing and development',
                'daily_rate' => 45.00,
                'image_url' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
                'category_id' => 1,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'processor' => 'Apple M2 Pro',
                    'ram' => '32GB',
                    'storage' => '1TB SSD',
                    'display' => '16-inch Retina',
                ]),
            ],
            [
                'name' => 'Dell XPS 15',
                'description' => 'Powerful Windows laptop with 4K display',
                'daily_rate' => 35.00,
                'image_url' => 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800',
                'category_id' => 1,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'good',
                'specifications' => json_encode([
                    'processor' => 'Intel i9-12900H',
                    'ram' => '32GB',
                    'storage' => '1TB SSD',
                    'display' => '15.6-inch 4K',
                ]),
            ],
            [
                'name' => 'Razer Blade 17',
                'description' => 'Gaming laptop with RTX 4080 graphics',
                'daily_rate' => 40.00,
                'image_url' => 'https://images.unsplash.com/photo-1544731612-de7f96afe55f?w=800',
                'category_id' => 1,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'new',
                'specifications' => json_encode([
                    'processor' => 'Intel i9-13900H',
                    'ram' => '32GB',
                    'storage' => '2TB SSD',
                    'graphics' => 'NVIDIA RTX 4080',
                ]),
            ],
            [
                'name' => 'Lenovo ThinkPad X1 Carbon',
                'description' => 'Business laptop with excellent keyboard and battery life',
                'daily_rate' => 30.00,
                'image_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800',
                'category_id' => 1,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'good',
                'specifications' => json_encode([
                    'processor' => 'Intel i7-1260P',
                    'ram' => '16GB',
                    'storage' => '512GB SSD',
                    'battery' => '15 hours',
                ]),
            ],
            
            // Cameras
            [
                'name' => 'Sony A7 IV',
                'description' => 'Professional mirrorless camera with 33MP sensor',
                'daily_rate' => 55.00,
                'image_url' => 'https://images.unsplash.com/photo-1516724562728-afc824a36e84?w=800',
                'category_id' => 2,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'sensor' => '33MP Full-frame',
                    'video' => '4K 60fps',
                    'stabilization' => '5-axis IBIS',
                    'autofocus' => 'Real-time tracking',
                ]),
            ],
            [
                'name' => 'Canon EOS R5',
                'description' => '45MP full-frame mirrorless camera with 8K video',
                'daily_rate' => 65.00,
                'image_url' => 'https://images.unsplash.com/photo-1523592121529-f6dde35f079e?w=800',
                'category_id' => 2,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'good',
                'specifications' => json_encode([
                    'sensor' => '45MP Full-frame',
                    'video' => '8K 30fps',
                    'stabilization' => '5-axis IBIS',
                    'autofocus' => 'Dual Pixel AF II',
                ]),
            ],
            [
                'name' => 'Fujifilm X-T5',
                'description' => 'Classic style mirrorless with excellent color science',
                'daily_rate' => 45.00,
                'image_url' => 'https://images.unsplash.com/photo-1581591524425-c7e0978865fc?w=800',
                'category_id' => 2,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'new',
                'specifications' => json_encode([
                    'sensor' => '40MP APS-C',
                    'video' => '6.2K 30fps',
                    'stabilization' => '5-axis IBIS',
                    'film_simulations' => '19 modes',
                ]),
            ],
            [
                'name' => 'Nikon Z9',
                'description' => 'Professional flagship mirrorless camera',
                'daily_rate' => 75.00,
                'image_url' => 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
                'category_id' => 2,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'sensor' => '45.7MP Full-frame',
                    'video' => '8K 60fps',
                    'burst' => '120fps',
                    'battery' => 'Extended life',
                ]),
            ],

            // Gaming Consoles
            [
                'name' => 'PlayStation 5',
                'description' => 'Latest gaming console from Sony with DualSense controller',
                'daily_rate' => 25.00,
                'image_url' => 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800',
                'category_id' => 3,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'storage' => '825GB SSD',
                    'resolution' => '4K 120Hz',
                    'ray_tracing' => 'Yes',
                    'includes' => 'DualSense controller',
                ]),
            ],
            [
                'name' => 'Xbox Series X',
                'description' => 'Microsoft\'s flagship gaming console',
                'daily_rate' => 25.00,
                'image_url' => 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800',
                'category_id' => 3,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'storage' => '1TB SSD',
                    'resolution' => '4K 120Hz',
                    'ray_tracing' => 'Yes',
                    'backward_compatibility' => 'Extensive',
                ]),
            ],
            [
                'name' => 'Nintendo Switch OLED',
                'description' => 'Hybrid gaming console with vibrant OLED screen',
                'daily_rate' => 20.00,
                'image_url' => 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800',
                'category_id' => 3,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'good',
                'specifications' => json_encode([
                    'screen' => '7-inch OLED',
                    'storage' => '64GB',
                    'battery' => '4.5-9 hours',
                    'includes' => 'Joy-Con controllers',
                ]),
            ],

            // Drones
            [
                'name' => 'DJI Mavic 3 Pro',
                'description' => 'Professional drone with Hasselblad camera',
                'daily_rate' => 75.00,
                'image_url' => 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?w=800',
                'category_id' => 4,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'camera' => '4/3 CMOS Hasselblad',
                    'flight_time' => '46 minutes',
                    'range' => '15km',
                    'max_speed' => '75km/h',
                ]),
            ],
            [
                'name' => 'DJI Mini 3 Pro',
                'description' => 'Compact drone under 250g with excellent camera',
                'daily_rate' => 45.00,
                'image_url' => 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800',
                'category_id' => 4,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'new',
                'specifications' => json_encode([
                    'weight' => '249g',
                    'camera' => '1/1.3" CMOS',
                    'flight_time' => '34 minutes',
                    'obstacle_sensing' => 'Tri-directional',
                ]),
            ],
            [
                'name' => 'Autel EVO II Pro',
                'description' => 'Professional drone with 6K camera',
                'daily_rate' => 65.00,
                'image_url' => 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800',
                'category_id' => 4,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'good',
                'specifications' => json_encode([
                    'camera' => '1" CMOS 6K',
                    'flight_time' => '40 minutes',
                    'range' => '9km',
                    'obstacle_avoidance' => 'Omnidirectional',
                ]),
            ],

            // Audio Equipment
            [
                'name' => 'Shure SM7B',
                'description' => 'Professional dynamic microphone',
                'daily_rate' => 20.00,
                'image_url' => 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800',
                'category_id' => 5,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'good',
                'specifications' => json_encode([
                    'type' => 'Dynamic',
                    'pattern' => 'Cardioid',
                    'frequency_response' => '50Hz-20kHz',
                    'impedance' => '150 ohms',
                ]),
            ],
            [
                'name' => 'Universal Audio Apollo Twin X',
                'description' => 'Professional audio interface with UAD processing',
                'daily_rate' => 35.00,
                'image_url' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800',
                'category_id' => 5,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'inputs' => '2 Mic/Line',
                    'processing' => 'QUAD Core',
                    'sample_rate' => 'Up to 192kHz',
                    'connection' => 'Thunderbolt 3',
                ]),
            ],
           

            // VR Headsets
            [
                'name' => 'Meta Quest 3',
                'description' => 'Advanced VR headset with controllers',
                'daily_rate' => 30.00,
                'image_url' => 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=800',
                'category_id' => 6,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'resolution' => '2064x2208 per eye',
                    'refresh_rate' => '120Hz',
                    'storage' => '256GB',
                    'includes' => 'Touch Plus controllers',
                ]),
            ],
            [
                'name' => 'Valve Index',
                'description' => 'High-end PC VR headset with finger tracking',
                'daily_rate' => 45.00,
                'image_url' => 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800',
                'category_id' => 6,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'good',
                'specifications' => json_encode([
                    'resolution' => '1440x1600 per eye',
                    'refresh_rate' => '144Hz',
                    'fov' => '130 degrees',
                    'tracking' => 'Base station 2.0',
                ]),
            ],
            [
                'name' => 'HP Reverb G2',
                'description' => 'High-resolution Windows Mixed Reality headset',
                'daily_rate' => 35.00,
                'image_url' => 'https://images.unsplash.com/photo-1622979135240-caa6648190b6?w=800',
                'category_id' => 6,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'new',
                'specifications' => json_encode([
                    'resolution' => '2160x2160 per eye',
                    'refresh_rate' => '90Hz',
                    'audio' => 'Off-ear speakers',
                    'tracking' => 'Inside-out',
                ]),
            ],

            // Additional Devices
            [
                'name' => 'ASUS ROG Strix G17',
                'description' => 'Premium gaming laptop with RTX 4090 and high refresh rate display',
                'daily_rate' => 50.00,
                'image_url' => 'https://images.unsplash.com/photo-1542393545-10f5cde2c810?w=800',
                'category_id' => 1,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'processor' => 'AMD Ryzen 9 7945HX',
                    'ram' => '64GB DDR5',
                    'storage' => '2TB NVMe SSD',
                    'graphics' => 'NVIDIA RTX 4090 16GB',
                    'display' => '17.3" QHD 240Hz',
                ]),
            ],
            [
                'name' => 'Blackmagic Pocket 6K Pro',
                'description' => 'Professional cinema camera with 6K resolution and dual native ISO',
                'daily_rate' => 85.00,
                'image_url' => 'https://images.unsplash.com/photo-1589872307627-e64c8d5aa0a2?w=800',
                'category_id' => 2,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'sensor' => 'Super 35 6K',
                    'iso_range' => '100-25600',
                    'recording' => 'Blackmagic RAW, ProRes',
                    'screen' => '5" Tilting HDR LCD',
                    'mount' => 'EF Mount',
                ]),
            ],
            [
                'name' => 'Neumann U87 Ai',
                'description' => 'Legendary studio microphone for professional vocal recording',
                'daily_rate' => 45.00,
                'image_url' => 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=800',
                'category_id' => 5,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'good',
                'specifications' => json_encode([
                    'type' => 'Large-diaphragm Condenser',
                    'patterns' => 'Omnidirectional, Cardioid, Figure-8',
                    'frequency_response' => '20Hz-20kHz',
                    'includes' => 'Shock mount, wooden box',
                ]),
            ],
            [
                'name' => 'DJI Ronin 4D',
                'description' => 'Professional 6K cinema camera with 4-axis stabilization',
                'daily_rate' => 95.00,
                'image_url' => 'https://images.unsplash.com/photo-1589872307627-e64c8d5aa0a2?w=800',
                'category_id' => 2,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'sensor' => 'Full-Frame 6K',
                    'stabilization' => '4-axis',
                    'focus' => 'LiDAR AF',
                    'transmission' => 'O3 Pro',
                    'storage' => 'CFexpress Type-B',
                ]),
            ],
            [
                'name' => 'Focusrite Clarett+ 8Pre',
                'description' => 'Professional 18-in, 20-out Thunderbolt audio interface',
                'daily_rate' => 40.00,
                'image_url' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800',
                'category_id' => 5,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'new',
                'specifications' => json_encode([
                    'inputs' => '8 mic preamps',
                    'outputs' => '10 line outputs',
                    'sample_rate' => 'Up to 192kHz',
                    'connection' => 'Thunderbolt 3',
                    'software' => 'Included plugin suite',
                ]),
            ],
            [
                'name' => 'Steam Deck OLED',
                'description' => 'Portable gaming PC with OLED display and enhanced performance',
                'daily_rate' => 30.00,
                'image_url' => 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800',
                'category_id' => 3,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => true,
                'condition' => 'new',
                'specifications' => json_encode([
                    'processor' => 'Custom AMD APU',
                    'storage' => '1TB NVMe SSD',
                    'display' => '7.4" HDR OLED',
                    'ram' => '16GB LPDDR5',
                    'controls' => 'Full gamepad + touchpads',
                ]),
            ],
            [
                'name' => 'Skydio 2+',
                'description' => 'Autonomous drone with advanced obstacle avoidance',
                'daily_rate' => 55.00,
                'image_url' => 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800',
                'category_id' => 4,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'new',
                'specifications' => json_encode([
                    'camera' => '4K/60fps HDR',
                    'autonomy' => 'Advanced AI navigation',
                    'flight_time' => '27 minutes',
                    'range' => '6km',
                    'tracking' => '360° obstacle avoidance',
                ]),
            ],
            [
                'name' => 'PICO 4 Enterprise',
                'description' => 'Professional VR headset for business and training',
                'daily_rate' => 40.00,
                'image_url' => 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=800',
                'category_id' => 6,
                'status' => Device::STATUS_AVAILABLE,
                'is_featured' => false,
                'condition' => 'new',
                'specifications' => json_encode([
                    'resolution' => '2160x2160 per eye',
                    'fov' => '105°',
                    'tracking' => 'Inside-out 6DoF',
                    'features' => 'Face/Eye tracking',
                    'comfort' => 'Balanced battery design',
                ]),
            ],
        ];

        foreach ($devices as $device) {
            Device::create($device);
        }
    }
} 